// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNuUpu41PKYBsbPTUGGKzHVhPNw9-Pmc',
    appId: '1:795878816417:web:your_web_app_id',
    messagingSenderId: '795878816417',
    projectId: 'linkcrypta-61258',
    authDomain: 'linkcrypta-61258.firebaseapp.com',
    storageBucket: 'linkcrypta-61258.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNuUpu41PKYBsbPTUGGKzHVhPNw9-Pmc',
    appId: '1:795878816417:android:16d6dc4eb1e0574bfecee0',
    messagingSenderId: '795878816417',
    projectId: 'linkcrypta-61258',
    storageBucket: 'linkcrypta-61258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNuUpu41PKYBsbPTUGGKzHVhPNw9-Pmc',
    appId: '1:795878816417:ios:your_ios_app_id',
    messagingSenderId: '795878816417',
    projectId: 'linkcrypta-61258',
    storageBucket: 'linkcrypta-61258.firebasestorage.app',
    iosBundleId: 'com.linkcrypta.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNuUpu41PKYBsbPTUGGKzHVhPNw9-Pmc',
    appId: '1:795878816417:macos:your_macos_app_id',
    messagingSenderId: '795878816417',
    projectId: 'linkcrypta-61258',
    storageBucket: 'linkcrypta-61258.firebasestorage.app',
    iosBundleId: 'com.linkcrypta.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTNuUpu41PKYBsbPTUGGKzHVhPNw9-Pmc',
    appId: '1:795878816417:windows:your_windows_app_id',
    messagingSenderId: '795878816417',
    projectId: 'linkcrypta-61258',
    authDomain: 'linkcrypta-61258.firebaseapp.com',
    storageBucket: 'linkcrypta-61258.firebasestorage.app',
  );
}
